# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.22.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.22.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gayuhkautaman/Documents/code/cpp/AES-KIJ

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gayuhkautaman/Documents/code/cpp/AES-KIJ

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.22.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.22.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gayuhkautaman/Documents/code/cpp/AES-KIJ/CMakeFiles /Users/gayuhkautaman/Documents/code/cpp/AES-KIJ//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gayuhkautaman/Documents/code/cpp/AES-KIJ/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AES-KIJ

# Build rule for target.
AES-KIJ: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AES-KIJ
.PHONY : AES-KIJ

# fast build rule for target.
AES-KIJ/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/build
.PHONY : AES-KIJ/fast

#=============================================================================
# Target rules for targets named AES-KIJ_autogen

# Build rule for target.
AES-KIJ_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AES-KIJ_autogen
.PHONY : AES-KIJ_autogen

# fast build rule for target.
AES-KIJ_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ_autogen.dir/build.make CMakeFiles/AES-KIJ_autogen.dir/build
.PHONY : AES-KIJ_autogen/fast

AES-KIJ_autogen/mocs_compilation.o: AES-KIJ_autogen/mocs_compilation.cpp.o
.PHONY : AES-KIJ_autogen/mocs_compilation.o

# target to build an object file
AES-KIJ_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/AES-KIJ_autogen/mocs_compilation.cpp.o
.PHONY : AES-KIJ_autogen/mocs_compilation.cpp.o

AES-KIJ_autogen/mocs_compilation.i: AES-KIJ_autogen/mocs_compilation.cpp.i
.PHONY : AES-KIJ_autogen/mocs_compilation.i

# target to preprocess a source file
AES-KIJ_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/AES-KIJ_autogen/mocs_compilation.cpp.i
.PHONY : AES-KIJ_autogen/mocs_compilation.cpp.i

AES-KIJ_autogen/mocs_compilation.s: AES-KIJ_autogen/mocs_compilation.cpp.s
.PHONY : AES-KIJ_autogen/mocs_compilation.s

# target to generate assembly for a file
AES-KIJ_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/AES-KIJ_autogen/mocs_compilation.cpp.s
.PHONY : AES-KIJ_autogen/mocs_compilation.cpp.s

libaes.o: libaes.cpp.o
.PHONY : libaes.o

# target to build an object file
libaes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/libaes.cpp.o
.PHONY : libaes.cpp.o

libaes.i: libaes.cpp.i
.PHONY : libaes.i

# target to preprocess a source file
libaes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/libaes.cpp.i
.PHONY : libaes.cpp.i

libaes.s: libaes.cpp.s
.PHONY : libaes.s

# target to generate assembly for a file
libaes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/libaes.cpp.s
.PHONY : libaes.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

nativeaes.o: nativeaes.cpp.o
.PHONY : nativeaes.o

# target to build an object file
nativeaes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/nativeaes.cpp.o
.PHONY : nativeaes.cpp.o

nativeaes.i: nativeaes.cpp.i
.PHONY : nativeaes.i

# target to preprocess a source file
nativeaes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/nativeaes.cpp.i
.PHONY : nativeaes.cpp.i

nativeaes.s: nativeaes.cpp.s
.PHONY : nativeaes.s

# target to generate assembly for a file
nativeaes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/nativeaes.cpp.s
.PHONY : nativeaes.cpp.s

server.o: server.cpp.o
.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i
.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s
.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AES-KIJ.dir/build.make CMakeFiles/AES-KIJ.dir/server.cpp.s
.PHONY : server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AES-KIJ_autogen"
	@echo "... AES-KIJ"
	@echo "... AES-KIJ_autogen/mocs_compilation.o"
	@echo "... AES-KIJ_autogen/mocs_compilation.i"
	@echo "... AES-KIJ_autogen/mocs_compilation.s"
	@echo "... libaes.o"
	@echo "... libaes.i"
	@echo "... libaes.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... nativeaes.o"
	@echo "... nativeaes.i"
	@echo "... nativeaes.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

